#!/bin/bash

for i in `ls -1 | grep -v "^*[_][D][0-9][0-9]*$"`
do
  for x in `seq 1 "$1"`
  do
    if [ "${x}" -lt 10 ]
    then
      out="0${x}"
    else
      out="${x}"
    fi
    cp $i ${i}_D${out}
  done
done
